### ISSUE TITLE
Saving path problem in Windows

### ISSUE THREAD

**Issue by NeuroLord** [SiTH-Diffusion/SiTH#9]
When running reconstruct.py, I encountered an error that prevents me from saving the obj mash to Windows due to creating double backslashes in the path. How can I fix this?
```
(sith) PS K:\Programs\sith> python reconstruct.py --test-folder data/examples --config recon/config.yaml --resume checkpoints/recon_model.pth
2024-07-14 19:23:02,896|    INFO| Info:
```{ 'dataset': { 'aug_jitter': False,
               'data_root': '../data/dataset.h5',
               'img_size': 1024,
               'num_samples': 20480,
               'white_bg': False},
  'embedder': {'color_freq': 0, 'shape_freq': 0},
  'global': { 'config': 'recon/config.yaml',
              'exp_name': 'train-recon',
              'log_level': 20,
              'resume': 'checkpoints/recon_model.pth',
              'save_root': '../checkpoints',
              'seed': 2434},
  'losses': { 'lambda_2D': 1.0,
              'lambda_nrm': 1.0,
              'lambda_rgb': 1.0,
              'lambda_sdf': 10.0,
              'use_mask': False,
              'use_pred_nrm': False},
  'network': { 'activation': 'lrelu',
               'feat_dim': 16,
               'hidden_dim': 512,
               'layer_type': 'none',
               'num_layers': 5,
               'pos_dim': 8,
               'skip': [2, 3, 4]},
  'optimizer': { 'beta1': 0.5,
                 'beta2': 0.999,
                 'lr_decoder': 0.001,
                 'lr_encoder': 0.0001,
                 'weight_decay': 0.0},
  'options': {'help': None, 'save_uv': False, 'test_folder': 'data/examples'},
  'positional arguments': {},
  'scheduler': { 'lr_num_cycles': 1,
                 'lr_power': 1.0,
                 'lr_scheduler': 'constant_with_warmup',
                 'lr_warmup_steps': 500,
                 'max_grad_norm': 1.0},
  'train': { 'batch_size': 8,
             'epochs': 5000,
             'log_every': 500,
             'save_every': 50,
             'workers': 8},
  'validation': { 'erode_iter': 0,
                  'grid_size': 512,
                  'num_valid_samples': 5,
                  'subdivide': True,
                  'valid': False,
                  'valid_every': 50,
                  'valid_folder': '../data/examples'},
  'wandb': {'wandb': False, 'wandb_id': None, 'wandb_name': 'train-recon'}}```
2024-07-14 19:23:04,750|    INFO| Initializing PIFu feature encoder...
2024-07-14 19:23:04,789|    INFO| Initializing neural field...
2024-07-14 19:23:04,796|    INFO| Initializing PIFu feature encoder...
2024-07-14 19:23:04,835|    INFO| Initializing neural field...
2024-07-14 19:23:12,315|    INFO| Reconstructing mesh for examples\images\000...
Traceback (most recent call last):
  File "K:\Programs\sith\reconstruct.py", line 67, in <module>
    main(args)
  File "K:\Programs\sith\reconstruct.py", line 52, in main
    evaluator.test_reconstruction(data, save_path, subdivide=args.subdivide, save_uv=args.save_uv)
  File "K:\Programs\sith\recon\models\evaluator.py", line 226, in test_reconstruction
    h.export(obj_path)
  File "F:\Programs\Anaconda\envs\sith\lib\site-packages\trimesh\base.py", line 2820, in export
    return export_mesh(mesh=self, file_obj=file_obj, file_type=file_type, **kwargs)
  File "F:\Programs\Anaconda\envs\sith\lib\site-packages\trimesh\exchange\export.py", line 55, in export_mesh
    file_obj = open(file_path, "wb")
FileNotFoundError: [Errno 2] No such file or directory: 'K:\\Programs\\sith\\data\\examples\\meshes\\examples\\images\\000_reco.obj'
```

**Comment by azuxmioy** [comment]
Sorry, I've never tried a Windows environment.

I'd suggest you use WSL in Windows.
